In [38]:
import pandas as pd
import numpy as np
from numpy import nan as NA
import os
from pathlib import Path
project_dir = Path.home().joinpath('Desktop\Git\Test\pydata-book-2nd-edition')


In [39]:
mnames = ['movie_id', 'title','genres']
file_dir = project_dir.joinpath('datasets/movielens/movies.dat')
movies = pd.read_table(file_dir,sep='::',header=None, names = mnames)
movies


C:\Users\kienn\AppData\Local\Temp\ipykernel_15888\2221239420.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table(file_dir,sep='::',header=None, names = mnames)


movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
3878                        Comedy  
3879                         Drama  
3880                         Drama  
3881                         Drama  
3882                Drama|Thriller  

[3883 rows x 3 columns]

In [40]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [41]:
zero_matrix = np.zeros((len(movies),len(genres)))
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
dummies = pd.DataFrame(zero_matrix,columns=genres)

In [43]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [50]:
 gen = movies.genres[0]
 gen.split('|')

['Animation', "Children's", 'Comedy']

In [48]:
dummies.columns.get_indexer(gen.split('|'))


array([0, 1, 2], dtype=int64)

In [49]:
dummies.columns

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='object')

In [58]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1
movies_windic = movies.join(dummies.add_prefix('Genres_'))
movies_windic.iloc[0]

movie_id                                        1
title                            Toy Story (1995)
genres                Animation|Children's|Comedy
Genres_Animation                              1.0
Genres_Children's                             1.0
Genres_Comedy                                 1.0
Genres_Adventure                              0.0
Genres_Fantasy                                0.0
Genres_Romance                                0.0
Genres_Drama                                  0.0
Genres_Action                                 0.0
Genres_Crime                                  0.0
Genres_Thriller                               0.0
Genres_Horror                                 0.0
Genres_Sci-Fi                                 0.0
Genres_Documentary                            0.0
Genres_War                                    0.0
Genres_Musical                                0.0
Genres_Mystery                                0.0
Genres_Film-Noir                              0.0


In [55]:
movies_windic

movie_id                               title  \
0            1                    Toy Story (1995)   
1            1                      Jumanji (1995)   
2            1             Grumpier Old Men (1995)   
3            1            Waiting to Exhale (1995)   
4            1  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878         1             Meet the Parents (2000)   
3879         1          Requiem for a Dream (2000)   
3880         1                    Tigerland (2000)   
3881         1             Two Family House (2000)   
3882         1               Contender, The (2000)   

                            genres  Genres_Animation  Genres_Children's  \
0      Animation|Children's|Comedy               1.0                1.0   
1     Adventure|Children's|Fantasy               0.0                1.0   
2                   Comedy|Romance               0.0                0.0   
3                     Comedy|Drama               0.0                0.0   
4                           Comedy               0.0                0.0   
...                            ...               ...                ...   
3878                        Comedy               0.0                0.0   
3879                         Drama               0.0                0.0   
3880                         Drama               0.0                0.0   
3881                         Drama               0.0                0.0   
3882                Drama|Thriller               0.0                0.0   

      Genres_Comedy  Genres_Adventure  Genres_Fantasy  Genres_Romance  \
0               1.0               0.0             0.0             0.0   
1               0.0               1.0             1.0             0.0   
2               1.0               0.0             0.0             1.0   
3               1.0               0.0             0.0             0.0   
4               1.0               0.0             0.0             0.0   
...             ...               ...             ...             ...   
3878            1.0               0.0             0.0             0.0   
3879            0.0               0.0             0.0             0.0   
3880            0.0               0.0             0.0             0.0   
3881            0.0               0.0             0.0             0.0   
3882            0.0               0.0             0.0             0.0   

      Genres_Drama  ...  Genres_Crime  Genres_Thriller  Genres_Horror  \
0              0.0  ...           0.0              0.0            0.0   
1              0.0  ...           0.0              0.0            0.0   
2              0.0  ...           0.0              0.0            0.0   
3              1.0  ...           0.0              0.0            0.0   
4              0.0  ...           0.0              0.0            0.0   
...            ...  ...           ...              ...            ...   
3878           0.0  ...           0.0              0.0            0.0   
3879           1.0  ...           0.0              0.0            0.0   
3880           1.0  ...           0.0              0.0            0.0   
3881           1.0  ...           0.0              0.0            0.0   
3882           1.0  ...           0.0              1.0            0.0   

      Genres_Sci-Fi  Genres_Documentary  Genres_War  Genres_Musical  \
0               0.0                 0.0         0.0             0.0   
1               0.0                 0.0         0.0             0.0   
2               0.0                 0.0         0.0             0.0   
3               0.0                 0.0         0.0             0.0   
4               0.0                 0.0         0.0             0.0   
...             ...                 ...         ...             ...   
3878            0.0                 0.0         0.0             0.0   
3879            0.0                 0.0         0.0             0.0   
3880            0.0                 0.0         0.0            

In [59]:
import re

In [61]:
text = "foo bar\t baz \tqux"
text

'foo bar\t baz \tqux'

In [62]:
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [63]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [64]:
regex = re.compile(pattern,flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [65]:
regex.search(text)

<re.Match object; span=(5, 20), match='dave@google.com'>

In [67]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
'Rob': 'rob@gmail.com', 'Wes': np.nan}
data1 = pd.Series(data)
data2 = pd.DataFrame(data,index = [1,2,3,4])

In [74]:
a1 = np.random.rand(2,3)
a2 = np.random.rand(1,3)

In [73]:
pd.DataFrame(a1,columns=['a','b','c'],index=['j','q'])

a         b         c
j  0.361536  0.685145  0.788306
q  0.030377  0.793553  0.449238

What is array?

In [83]:
np.empty([3,2])

array([[3.18299369e-313, 3.18299369e-313],
       [3.18299369e-313, 3.18299369e-313],
       [3.18299369e-313, 3.18299369e-313]])

In [84]:
np.zeros([3,2], dtype= int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [86]:
a = np.asarray([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
b = np.asarray(range(9))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
a[1,2]

6

In [96]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
y

array([1, 4, 5])

In [99]:
x[x>4]

array([5, 6])